// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MoToSale.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606090000_NormalizeAdminOrderStatuses")]
    partial class NormalizeAdminOrderStatuses
    {
    }
}
